        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 12:39:27 2014
        MODULE TEST_READ_INPUTS_GENERATE__genmod
          INTERFACE 
            SUBROUTINE TEST_READ_INPUTS_GENERATE
            END SUBROUTINE TEST_READ_INPUTS_GENERATE
          END INTERFACE 
        END MODULE TEST_READ_INPUTS_GENERATE__genmod
