        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 12:39:27 2014
        MODULE TEST_DECOHERENCE_INPUTS__genmod
          INTERFACE 
            SUBROUTINE TEST_DECOHERENCE_INPUTS
            END SUBROUTINE TEST_DECOHERENCE_INPUTS
          END INTERFACE 
        END MODULE TEST_DECOHERENCE_INPUTS__genmod
