        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 12:39:27 2014
        MODULE TEST_READ_OUTPUTS__genmod
          INTERFACE 
            SUBROUTINE TEST_READ_OUTPUTS
            END SUBROUTINE TEST_READ_OUTPUTS
          END INTERFACE 
        END MODULE TEST_READ_OUTPUTS__genmod
